library("rhdf5")
library("rtracklayer")
library("ggnewscale")
library("Rphenograph")
library("irlba")
library("Rcpp")
library("umap")
library("ggplot2")
library("pheatmap")
library("gridExtra")
library("grid")
library("patchwork")
library("lattice")
library("cowplot")
library("plotly")
library("janitor")
library("data.table")
library("readr")
library("tidyverse")
library("tibble")
library("plyr")
library("tidyr")
library("Rmagic")
library("future")
library("furrr")
library("purrr")
library("dplyr")


pal <- c("#004A4A", "#F05252", "#419e9e", "#fcba2b", "#bd083e", "#FB9A99", "#75C8D2",  "#FF8B73", "#B2DF8A", "#1F78B4", "#E31A1C",  "#aae3e3",  "#FFA976")
options(scipen = 999)
options(future.globals.maxSize = (20000*1024^2)) # 10 GB
